---
title: ""
format:
  html:
    toc: false
    anchor-sections: false
---

## Conteúdo

1. Modelo Probabilístico para um experimento aleatório

    1.1. Experimento Aleatório
    
    1.2. Espaço Amostral
    
    1.3. Evento


2.  Revisão básica de teoria de conjuntos

    2.1. Conjuntos, elementos
    
    2.2. Operações entre conjuntos

3. Técnicas de Contagem

    3.1. Permutação ou Arranjo simples e com repetição
    
    3.2. Permutação Circular
    
    3.3. Combinação simples e com repetição

4. Definições e espaços de Probabilidade

    4.1. Classes de Conjuntos: sigma-álgebra
    
    4.2. Definições de Probabilidade
    
    4.3. Definição frequentista
    
    4.4. Definição Geométrica
    
    4.5. Definição Clássica
    
    4.6. Axiomas de Kolmogorov

5. Probabilidade Condicional e Independência

    5.1. Probabilidade condicional
    
    5.2. Regra do Produto de Probabilidades
    
    5.3. Lei da Probabilidade Total
    
    5.4. Diagrama de árvore
    
    5.5. Partição do espaço amostral
    
    5.6. Teorema de Bayes
    
    5.7. Independência de dois eventos
    
    5.8. Independência de vários eventos


6. Variável aleatória discreta

    6.1. Função de distribuição de variáveis aleatórias discretas
    
    6.2. Variável Aleatória Discreta
    
    6.3. Função de Probabilidade e suas propriedades
    
    6.4. Função de Distribuição ou Função Acumulada de probabilidade
    
    6.5. Esperança e Variância de uma V.A.D.
    
    6.6. Variável Aleatória Discreta: Bidimensional